<?xml version="1.0" encoding="UTF-8"?>

<!-- Copyright (c) 2007 IBM Corporation and others. All rights reserved -->

<!-- Test data file for string search  -->
<!DOCTYPE stringsearch-tests [
<!ELEMENT stringsearch-tests (test-case+)>
<!ELEMENT test-case (pattern, pre?, m?, post?)>
<!ATTLIST test-case 
          id ID #REQUIRED
          locale NMTOKEN "en" 
          strength (PRIMARY | SECONDARY | TERTIARY | QUATERNARY) "TERTIARY"  >

<!ELEMENT pattern (#PCDATA)>
<!ELEMENT pre  (#PCDATA)>
<!ELEMENT m    (#PCDATA)>
<!ELEMENT post (#PCDATA)>
]>

<stringsearch-tests>
  <test-case id="test06" strength="SECONDARY" >
      <pattern>fuß</pattern>
       <pre></pre><m>fuss</m><post></post>
    </test-case>
    <!--
    <test-case id="test01" >
       <pattern>abc</pattern>
       <pre>xxx</pre><m>abc</m><post>yyy</post>
    </test-case>
    
    <test-case id="test02" >
       <pattern>abc</pattern>
       <pre>xxx</pre><post>yyy</post>
    </test-case>

    <test-case id="test03" >
       <pattern>string</pattern>
       <pre>silly spring </pre><m>string</m><post> fling</post>
    </test-case>
    
    <test-case id="test04" strength="PRIMARY" >
       <pattern>FUSS</pattern>
       <pre>abc</pre><m>fuss</m><post>sss</post>
    </test-case>
    
    <test-case id="test05" strength="PRIMARY" >
       <pattern>FUSS</pattern>
       <pre>abc</pre><m>fuß</m><post>sss</post>
    </test-case>
    -->
   
  </stringsearch-tests>
  
